Boardshare/Boardshare

.gitignore
bower.json
gulpfile.js
package.json

bower components & node modules

add dependencies

---

client/app/entry.js
gulpfile.js
package.json

Gulpfile now handles changes to stylesheets and scripts. Uses browserify for frontend dependencies.

Edit gulpfile

---

.jshintrc
client/app/canvas/canvas.handlebars
client/app/canvas/canvas.js
client/app/canvas/canvasHelpers/drawGrid.js
client/app/canvas/canvasHelpers/getCoords.js
client/app/canvas/canvasHelpers/mouseActions.js
client/app/canvas/canvasHelpers/saveAndRestore.js
client/app/canvas/canvasHelpers/windowToCanvas.js
client/app/entry.js
client/app/helpers/getTemplates.js
client/app/helpers/renderTemplates.js
client/app/helpers/resizeElement.js
client/app/helpers/setImmediate.js
client/assets/css/canvas.css
client/index.html

Added Custom Event Handler for Template Rendering.
Added Base UI for canvas options.
Created a bunch of canvas helper functions
Added Event Handlers for canvas.

Paint canvas

---

client/app/editor/editor.handlebars
client/app/editor/editor.js
client/assets/css/editor.css
client/index.html

editor.handlebars
editor.js
editor.css
index.html

everything

---

client/app/helpers/peerConnection.js
client/app/video/video.handlebars
client/app/video/video.js
client/assets/css/video.css

* users no longer accept calls when their cam is off  
* users can join call in any order and everything works  
* remove window variable for stream

robustify call handling

---

client/app/board.html
client/app/canvas/canvas.js
client/app/helpers/remotePeer.js
client/app/helpers/renderTemplates.js

Canvas now has real time updating.

have state updating between clients

---

client/app/canvas/canvas.js

fixed brush updating color/width

---

client/app/board.html
client/app/canvas/canvas.js
client/app/helpers/peerConnection.js
server/routes/routes.js
server/utils/boardShare.js
server/utils/boardShares.js
server/utils/connectionHandlers.js

fix board url issue stemming from ids with length < 7

---

.gitignore
gulpfile.js
package.json
test/client/Runner.html
test/client/customEventPolyfill.js
test/client/editorSpec.js
test/client/entrySpec.js
test/client/messagingSpec.js

Browserify tests

---

client/app/board.html
client/app/canvas/canvas.handlebars
client/app/editor/editor.handlebars
client/app/editor/editor.js
client/assets/css/canvas.css
client/assets/css/editor.css
client/assets/css/messaging.css
client/assets/css/video.css

Reverts Boardshare/Boardshare#52

Revert "Layout"

---

client/app/board.html
client/app/editor/editor.handlebars
client/app/editor/editor.js
client/assets/css/editor.css

editor working now back and forth completely

---

.gitignore
client/app/helpers/remotePeer.js
gulpfile.js
package.json

also,
update gulpfile for doxx and add dependenices
add comments for documentation to remotePeer.js
typo fix

add doxx for generating documentation

---

.gitignore
client/app/helpers/peerHelpers.js
client/app/helpers/remotePeer.js
client/app/helpers/remotePeers.js
gulpfile.js

complete documentation of peerHelpers, remotePeer, remotePeers

---

client/app/canvas/canvas.handlebars
client/app/canvas/canvas.js
client/app/canvas/canvasHelpers/getBrushes.js
client/app/canvas/canvasHelpers/getSelectors.js
client/app/canvas/canvasHelpers/makeColorInputs.js
client/app/canvas/canvasHelpers/modes.js
client/app/canvas/canvasHelpers/mouseEvents.js
client/app/canvas/canvasHelpers/shapes.js
client/app/canvas/canvasHelpers/stateManager.js
client/app/canvas/canvasHelpers/uploadImage.js
client/app/canvas/canvasHelpers/utils.js
gulpfile.js

Removed eraser tool
State updates when an object is modified now
User can delete a selected object
User can copy a selected object

Paint canvas selection

---

client/app/board.html
client/app/editor/editor.handlebars
client/app/editor/editor.js
client/assets/css/editor.css
client/assets/css/layout.css
client/index.html

layout is moved to landing page and old code has been deleted from board.html

Refactor layout

---

client/app/board.html
client/app/canvas/canvas.handlebars
client/app/canvas/canvas.js
client/app/canvas/canvasHelpers/mouseEvents.js
client/app/canvas/canvasHelpers/stateManager.js
client/app/helpers/remotePeer.js
client/assets/css/layout.css
client/index.html
gulpfile.js

Fixed file paths in the dist folder to correctly grab fonts/css/js
Fixed database having to save the entire state
Clearing the canvas now resets the state with just the previous state and the current blank one
The canvas state is not transmitted on each draw, and instead just the current state is sent
Maybe fixed multiple people drawing at once interupting you. Don't know until it is tested.

Optimize code

---

client/app/canvas/canvasHelpers/stateManager.js
client/app/peer/remotePeer.js

Quick and dirty fix for the selection bug.

hotfix for selection bug

---

client/app/board.html
client/app/profile/profile.html
client/app/profile/profile.js
server/routes/auth.js
server/routes/routes.js

The entire profile is completed but needs styling.
The login feature now works and redirects to the board from whence the user came.  Needs styling.

profile & login

---

client/app/profile/profile.html
client/app/profile/profile.js
server/routes/auth.js

got rid off excess stuff; moved scripts out of html

---

client/app/entry.js
client/app/helpers/renderTemplates.js
client/app/profile/profile.html
client/app/profile/profile.js
gulpfile.js

removed inline script and fixed the consequences

---

client/app/board.html
client/app/canvas/canvasHelpers/modes.js
client/app/editor/editor.js
client/app/helpers/app.ui.js
client/app/messaging/messaging.js
package.json

login button turns into logout for authed user
